services:
  postgres:
    image: postgres:17
    container_name: event_postgres
    restart: always
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
      POSTGRES_DB: eventdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Port local:container
    networks:
      - eventnet

  backend:
    build: ./TP_EVENT_API
    container_name: event_backend
    image: ghcr.io/samwin25/eventapp-backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: eventuser
      DB_PASSWORD: eventpass
      DB_NAME: eventdb
      PORT: 9002
    ports:
      - "9002:9002"
    networks:
      - eventnet

  frontend:
    build: ./TP_EVENT_WEB_APP
    container_name: event_frontend
    image: ghcr.io/samwin25/eventapp-frontend
    depends_on:
      - backend
    ports:
      - "8082:8082"
    environment:
      - REACT_APP_API_URL=http://backend:9002
    networks:
      - eventnet

volumes:
  pgdata:

networks:
  eventnet:
    driver: bridge
