name: Build and Push Docker Images

on:
  push:
    branches:
      - myevent-app-samson
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push backend
        run: |
          docker build -t ghcr.io/${{ github.actor }}/eventapp-backend:latest ./TP_EVENT_API
          docker push ghcr.io/${{ github.actor }}/eventapp-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t ghcr.io/${{ github.actor }}/eventapp-frontend:latest ./TP_EVENT_WEB_APP
          docker push ghcr.io/${{ github.actor }}/eventapp-frontend:latest
