name: Build and Push Docker Images

on:
  push:
    branches:
      - myevent-app-samson
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Git State
        run: |
          git status
          git log -1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # .github/workflows/build-and-push.yml
      - name: Build and push backend
        run: |
          docker build -t ghcr.io/${{ github.actor }}/eventapp-backend ./TP_EVENT_API
          docker push ghcr.io/${{ github.actor }}/eventapp-backend

      - name: Build and push frontend
        run: |
         docker build -t ghcr.io/${{ github.actor }}/eventapp-frontend ./TP_EVENT_WEB_APP
         docker push ghcr.io/${{ github.actor }}/eventapp-frontend


